=== RomainMHR/code_generator/minispec.dtd
<!ELEMENT model (entity*)>
<!ATTLIST model 
    name CDATA #REQUIRED
>

<!ELEMENT entity (attribute*)>
<!ATTLIST entity 
    name CDATA #REQUIRED
    extends CDATA #IMPLIED
>

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute 
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    collection (List|Set|Bag|Array) #IMPLIED
    min CDATA #IMPLIED
    max CDATA #IMPLIED
>

=== RomainMHR/code_generator/satellite.xml
<!DOCTYPE model SYSTEM "minispec.dtd">
<model name="minispec.space">

    <entity name="EnginSpatial">
        <attribute name="id" type="Integer"/>
        <attribute name="poids" type="Integer"/>

    </entity>

    <entity name="Satellite" extends="EnginSpatial">
        <attribute name="nom" type="String"/>
        <attribute name="parent" type="Flotte"/>
    </entity>

    <entity name="Fusée" extends="EnginSpatial">
        <attribute name="puissance" type="Integer"/>
    </entity>

    <entity name="Flotte">
        <attribute name="vaisseaux" type="EnginSpatial" collection="List" min="0" max="50"/>
    	<attribute name="fusee" type="Fusée" collection="Array" min="2" max="2"/>
    </entity>

</model>
